# SPDX-FileCopyrightText: Contributors to the Power Grid Model project <powergridmodel@lfenergy.org>
#
# SPDX-License-Identifier: MPL-2.0

repos:
  - repo: local
    hooks:
      - id: reuse
        name: reuse
        entry: uv run --frozen reuse lint
        language: system
        pass_filenames: false