name: Sync example notebooks from main PGM repo to PGM-workshop

on:
  push:
    branches:
      - sync-examples-workflow
  workflow_dispatch:
  schedule:
    - cron: "32 14 * * *" # Based on UTC time

jobs:
  sync-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PGM workshop repository
        uses: actions/checkout@v4

      - name: Checkout PGM Repository
        uses: actions/checkout@v4
        with:
          repository: PowerGridModel/power-grid-model
          ref: main

      # - name: Copy examples to PGM-workshop repo
      #   uses: nkoppel/push-files-to-another-repository@1.1.0
      #   env:
      #     API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      #   with:
      #     source-files: 'docs/examples/'
      #     destination-username: 'Power Grid Model'
      #     destination-repository: 'power-grid-model-workshop'
      #     destination-branch: 'feature/sync-examples-workflow'
      #     destination-directory: 'examples/'
      #     commit-email: 'action@github.com'

      - name: Copy Files
        run: |
          cp -r docs/examples $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE/examples
          ls

      - name: Display $GITHUB_WORKSPACE contents
        run: |
          ls $GITHUB_WORKSPACE

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11   

      - name: Checkout PGM workshop repository
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate 
          pip install -r requirements.txt

      - name: Run the notebooks
        run: |
          source venv/bin/activate

          jupyter nbconvert --to notebook --execute $GITHUB_WORKSPACE

      - name: Commit and Push Changes to PGM workshop repository
        run: |
          git config user.name 'GitHub Action'
          git config user.email 'action@github.com'
          git add .

          if git diff-index --quiet HEAD; then
            echo "No changes detected."
          else
            git commit -m "Update PGM examples"
            git push
