name: Sync example notebooks from main PGM repo to PGM-workshop

on:
  push:
    branches:
      - sync-examples-workflow
  workflow_dispatch:
  schedule:
    - cron: "32 14 * * *" # Based on UTC time

jobs:
  sync-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PGM workshop repository
        uses: actions/checkout@v4
        with:
          path: power-grid-model-workshop

      - name: Checkout PGM Repository examples
        uses: actions/checkout@v4
        with:
          repository: PowerGridModel/power-grid-model
          ref: main
          path: power-grid-model
          sparse-checkout: docs/examples
          sparse-checkout-cone-mode: false

      - name: Display $GITHUB_WORKSPACE contents
        run: |
          ls $GITHUB_WORKSPACE

      - name: Move pgm examples to pgm workshop repository
        run: |
          ls power-grid-model-workshop
          rm -rf power-grid-model-workshop/examples
          mv power-grid-model/docs/examples power-grid-model-workshop
          ls power-grid-model-workshop

      - name: Display $GITHUB_WORKSPACE contents
        run: |
          ls $GITHUB_WORKSPACE

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11   

      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate 
          pip install -r requirements.txt
        working-directory: power-grid-model-workshop

      - name: Run the notebooks
        run: |
          source venv/bin/activate

          jupyter nbconvert --to notebook --execute $GITHUB_WORKSPACE
        working-directory: power-grid-model-workshop

      - name: Commit and Push Changes to PGM workshop repository
        run: |
          git config user.name 'GitHub Action'
          git config user.email 'action@github.com'
          git add .

          if git diff-index --quiet HEAD; then
            echo "No changes detected."
          else
            git commit -m "Update PGM examples"
            git push
        working-directory: power-grid-model-workshop
